//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkerSearcher.Computrabajo.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WorkerSearcher.Computrabajo.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El valor de query no puede ser vacio.
        /// </summary>
        internal static string ErrorEmptyQuery {
            get {
                return ResourceManager.GetString("ErrorEmptyQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string MaxNavigate {
            get {
                return ResourceManager.GetString("MaxNavigate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.computrabajo.com.pe/empleos-en-lima.
        /// </summary>
        internal static string Page1 {
            get {
                return ResourceManager.GetString("Page1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.computrabajo.com.pe/empleos-de-informatica-y-telecom-en-lima.
        /// </summary>
        internal static string Page2 {
            get {
                return ResourceManager.GetString("Page2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.computrabajo.com.pe/empleos-de-ingenieria-y-tecnico-en-lima.
        /// </summary>
        internal static string Page3 {
            get {
                return ResourceManager.GetString("Page3", resourceCulture);
            }
        }
    }
}
